url: https://buildah.io
theme: jekyll-theme-dinky

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false

excerpt_separator: "<!--readmore-->"

authors:
  dwalsh:
    name: Dan Walsh 
    display_name: Dan Walsh
    gravatar: 75d88487c07b14b6c7aa0599fce600bf
    email: dwalsh@redhat.com
    web: https://people.redhat.com/dwalsh/
    twitter: rhatdan
    github: rhatdan
  ipbabble:
    name: William Henry
    display_name: ipbabble
    gravatar: 
    email: whenry@redhat.com
    web: https://redhat.com
    twitter: ipbabble
    github: ipbabble
  tsweeney:
    name: Tom Sweeney 
    display_name: Tom Sweeney
    gravatar: c69c8419c8e4d1bbedc7874281453781 
    email: tsweeney@redhat.com
    web: https://redhat.com
    twitter: TSweeneyRedHat
    github: TomSweeneyRedhat
  emacchi:
    name: Emilien Macchi
    display_name: Emilien Macchi
    gravatar: 01b814c7bee867b3626b5a474925e183
    email: emilien@redhat.com
    web: http://my1.fr/blog
    twitter: EmilienMacchi
    github: EmilienM
