theme: jekyll-theme-hacker

baseurl: /buildah.io

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-readme-index
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false

excerpt_separator: "<!--readmore-->"
